In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings


heart = pd.read_csv('heart.csv')

# Exploring data

In [27]:
heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [6]:
heart['Sex']=heart['Sex'].map({"M":1,"F":0})

In [7]:
heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,0,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,1,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,0,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,1,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [8]:
df_heart = heart.copy()
df_heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,0,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,1,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,0,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,1,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [29]:
df_heart =  pd.get_dummies(df_heart,columns= ['ChestPainType'],drop_first=False)
df_heart.head()

KeyError: "None of [Index(['ChestPainType'], dtype='object')] are in the [columns]"

In [30]:
df_heart =  pd.get_dummies(df_heart,columns= ['RestingECG'],drop_first=False)
df_heart.head()

KeyError: "None of [Index(['RestingECG'], dtype='object')] are in the [columns]"

In [31]:
df_heart['ExerciseAngina'] = df_heart['ExerciseAngina'].map({"Y":1, "N":0})

In [32]:
print(df_heart.columns.tolist())

['Age', 'Sex', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'HeartDisease', 'ChestPainType_ASY', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_LVH', 'RestingECG_Normal', 'RestingECG_ST', 'ST_Slope_Down', 'ST_Slope_Flat', 'ST_Slope_Up']

In [33]:
type(df_heart)

pandas.core.frame.DataFrame

In [34]:
df_heart.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,NaN,0.0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,NaN,1.0,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,NaN,0.0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,NaN,1.5,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,NaN,0.0,0,0,0,1,0,0,1,0,0,0,1

In [35]:
bool_col = df_heart.select_dtypes(include='bool').columns
df_heart[bool_col] = df_heart[bool_col].astype(int)

In [36]:
df_heart['ST_Slope'].unique()

KeyError: 'ST_Slope'

In [37]:
df_heart.dtypes

Age                    int64
Sex                    int64
RestingBP              int64
Cholesterol            int64
FastingBS              int64
MaxHR                  int64
ExerciseAngina       float64
Oldpeak              float64
HeartDisease           int64
ChestPainType_ASY      int64
ChestPainType_ATA      int64
ChestPainType_NAP      int64
ChestPainType_TA       int64
RestingECG_LVH         int64
RestingECG_Normal      int64
RestingECG_ST          int64
ST_Slope_Down          int64
ST_Slope_Flat          int64
ST_Slope_Up            int64
dtype: object

In [38]:
df_heart = pd.get_dummies(df_heart,columns =['ST_Slope'], drop_first = False)

KeyError: "None of [Index(['ST_Slope'], dtype='object')] are in the [columns]"

In [39]:
bol_col = df_heart.select_dtypes(include='bool').columns
df_heart[bol_col] = df_heart[bol_col].astype(int)

In [40]:
df_heart.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,NaN,0.0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,NaN,1.0,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,NaN,0.0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,NaN,1.5,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,NaN,0.0,0,0,0,1,0,0,1,0,0,0,1

In [41]:
df_heart.dtypes

Age                    int64
Sex                    int64
RestingBP              int64
Cholesterol            int64
FastingBS              int64
MaxHR                  int64
ExerciseAngina       float64
Oldpeak              float64
HeartDisease           int64
ChestPainType_ASY      int64
ChestPainType_ATA      int64
ChestPainType_NAP      int64
ChestPainType_TA       int64
RestingECG_LVH         int64
RestingECG_Normal      int64
RestingECG_ST          int64
ST_Slope_Down          int64
ST_Slope_Flat          int64
ST_Slope_Up            int64
dtype: object

In [42]:
df_heart.value_counts().sum()

np.int64(0)

In [43]:
df_heart['Age'].isna().sum()

np.int64(0)

In [44]:
for col in df_heart.columns:
    null_count = df_heart[col].isna().sum()
    if null_count>0:
        print(col,null_count)

ExerciseAngina 918

In [45]:
df_heart.shape

(918, 19)