In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings


heart = pd.read_csv('heart.csv')

# Exploring data

In [16]:
heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [17]:
heart['Sex']=heart['Sex'].map({"M":1,"F":0})

In [18]:
heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,0,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,1,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,0,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,1,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [19]:
df_heart = heart.copy()
df_heart.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,0,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,1,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,0,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,1,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [20]:
df_heart =  pd.get_dummies(df_heart,columns= ['ChestPainType'],drop_first=False)
df_heart.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA
0,40,1,140,289,0,Normal,172,N,0.0,Up,0,False,True,False,False
1,49,0,160,180,0,Normal,156,N,1.0,Flat,1,False,False,True,False
2,37,1,130,283,0,ST,98,N,0.0,Up,0,False,True,False,False
3,48,0,138,214,0,Normal,108,Y,1.5,Flat,1,True,False,False,False
4,54,1,150,195,0,Normal,122,N,0.0,Up,0,False,False,True,False

In [21]:
df_heart =  pd.get_dummies(df_heart,columns= ['RestingECG'],drop_first=False)

In [22]:
df_heart['ExerciseAngina'] = df_heart['ExerciseAngina'].map({"Y":1, "N":0})

In [30]:
df_heart.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,0,1.0,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,0,0.0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,1,1.5,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,0,0.0,0,0,0,1,0,0,1,0,0,0,1

In [23]:
print(df_heart.columns.tolist())

['Age', 'Sex', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope', 'HeartDisease', 'ChestPainType_ASY', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_LVH', 'RestingECG_Normal', 'RestingECG_ST']

In [24]:
df_heart.dtypes

Age                    int64
Sex                    int64
RestingBP              int64
Cholesterol            int64
FastingBS              int64
MaxHR                  int64
ExerciseAngina         int64
Oldpeak              float64
ST_Slope              object
HeartDisease           int64
ChestPainType_ASY       bool
ChestPainType_ATA       bool
ChestPainType_NAP       bool
ChestPainType_TA        bool
RestingECG_LVH          bool
RestingECG_Normal       bool
RestingECG_ST           bool
dtype: object

In [25]:
df_heart.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST
0,40,1,140,289,0,172,0,0.0,Up,0,False,True,False,False,False,True,False
1,49,0,160,180,0,156,0,1.0,Flat,1,False,False,True,False,False,True,False
2,37,1,130,283,0,98,0,0.0,Up,0,False,True,False,False,False,False,True
3,48,0,138,214,0,108,1,1.5,Flat,1,True,False,False,False,False,True,False
4,54,1,150,195,0,122,0,0.0,Up,0,False,False,True,False,False,True,False

In [26]:
bool_col = df_heart.select_dtypes(include='bool').columns
df_heart[bool_col] = df_heart[bool_col].astype(int)

In [27]:
df_heart['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [28]:
njdf_heart = pd.get_dummies(df_heart,columns =['ST_Slope'], drop_first = False)

In [29]:
bol_col = df_heart.select_dtypes(include='bool').columns
df_heart[bol_col] = df_heart[bol_col].astype(int)

In [ ]:
df_heart.value_counts().sum()

np.int64(0)

In [ ]:
df_heart['Age'].isna().sum()

np.int64(0)

In [ ]:
for col in df_heart.columns:
    null_count = df_heart[col].isna().sum()
    if null_count>0:
        print(col,null_count)

ExerciseAngina 918

In [33]:
df_heart.shape

(918, 19)

In [34]:
df_heart.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,0,1,0,0,0,1,0,0,0,1
1,49,0,160,180,0,156,0,1.0,1,0,0,1,0,0,1,0,0,1,0
2,37,1,130,283,0,98,0,0.0,0,0,1,0,0,0,0,1,0,0,1
3,48,0,138,214,0,108,1,1.5,1,1,0,0,0,0,1,0,0,1,0
4,54,1,150,195,0,122,0,0.0,0,0,0,1,0,0,1,0,0,0,1

generating all the models at once namely
**bold text**

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [37]:
X = df_heart.drop('HeartDisease',axis = 1)
y = df_heart['HeartDisease']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [43]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [49]:
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Decision Tree': DecisionTreeClassifier(),
    'SVM': SVC(),
    'KNN': KNeighborsClassifier()
}
result = []

In [50]:
for x in models:
  model =models[x]
  model.fit(X_train_scaled,y_train)
  y_pred = model.predict(X_test_scaled)
  accur = accuracy_score(y_test,y_pred)
  f1 = f1_score(y_test,y_pred)
  result.append(
      {
          'model': x,
          'accuracy':round(accur,4),
          'f1_score':round(f1,4)
      }
  )

In [51]:
result

[{'model': 'Logistic Regression', 'accuracy': 0.8587, 'f1_score': 0.875},
 {'model': 'Naive Bayes', 'accuracy': 0.8587, 'f1_score': 0.875},
 {'model': 'Decision Tree', 'accuracy': 0.8207, 'f1_score': 0.8406},
 {'model': 'SVM', 'accuracy': 0.8859, 'f1_score': 0.9014},
 {'model': 'KNN', 'accuracy': 0.8641, 'f1_score': 0.8792}]

In [53]:
import joblib

joblib.dump(models['KNN'], 'KNN_heart.pkl')   # Saves the trained KNN model
joblib.dump(scaler, 'scaler.pkl')             # Saves the fitted scaler (used for preprocessing)

['scaler.pkl']